/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/NEWSheepModelwAnimations3.gltf"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Bone} />
          <skinnedMesh 
            name="Sheep"
            geometry={nodes.Sheep.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Sheep.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/NEWSheepModelwAnimations3.gltf");