/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useState } from "react";
import { useGLTF, useAnimations, useCursor } from "@react-three/drei";

/* skeleton utils */
import { SkeletonUtils } from "three-stdlib";
import { useGraph } from "@react-three/fiber";

/* future me, confused what's going on? worry not, reference this bad boi: https://codesandbox.io/s/gltf-animations-re-used-k8phr?file=/src/Model.js:598-635 */

export default function Model(props) {
  const group = useRef();
  const { materials, animations, scene } = useGLTF(
    "/NEWSheepModelwAnimations3.gltf"
  );
  const { actions } = useAnimations(animations, group);

  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone)

  //sets initial color of sheep
  const randomColor = getRandomColor();
  // Upon click, changes color
  const [sheepColor, setSheepColor] = useState(randomColor);
  function getRandomColor() {
    let letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}


  // //receive sheep color
  // const sheepColor = props.color;
  console.log(props);

  // Hover 
  const [hovered, setHovered] = useState(false);
  // Change cursor on hover-state
  useCursor(hovered);


  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Armature"
            onPointerOver={() => setHovered(true)}
            onPointerOut={() => setHovered(false)}
            onClick={() => setSheepColor(sheepColor => getRandomColor())} >
            <primitive object={nodes.Bone} />
            <skinnedMesh 
              name="Sheep"
              geometry={nodes.Sheep.geometry}
              // material={materials["Material.001"]}
              skeleton={nodes.Sheep.skeleton}
            >
              <meshStandardMaterial color={sheepColor} />
            </skinnedMesh>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/NEWSheepModelwAnimations3.gltf");