/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from '@react-three/fiber';
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Sheep({ ...props }) {
  const mesh = useRef();
  const { nodes } = useGLTF("/sheepModel.gltf");
  const materials = new THREE.MeshStandardMaterial({ color: "red" })
  useFrame((state, delta) => (mesh.current.rotation.y += 0.01));

  return (
    <group {...props} dispose={null}>
      <mesh ref={mesh}
        castShadow
        receiveShadow
        geometry={nodes.Sheep.geometry}
        material={materials}
        position={[0, -0.5, 3.5]}
      />
    </group>
  );
}

useGLTF.preload("/sheepModel.gltf");