/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from '@react-three/fiber';
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

function getRandomColor() {
    var letters = '0123456789ABCDEF';
    var color = '#';
    for (var i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

export default function Sheep({ ...props }) {
  const mesh = useRef();
  const { nodes } = useGLTF("/sheepModel.gltf");
  const materials = new THREE.MeshStandardMaterial({ color: getRandomColor() })
  
  {/* makes sheep rotate */}
  useFrame((state, delta) => (mesh.current.rotation.y += 0.01));

  return (
    <group {...props} dispose={null}>
      <mesh ref={mesh}
        castShadow
        receiveShadow
        geometry={nodes.Sheep.geometry}
        material={materials}
        position={[0, -0.5, 3.5]}
      />
    </group>
  );
}

useGLTF.preload("/sheepModel.gltf");