/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useFrame } from '@react-three/fiber';
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

function getRandomColor() {
    let letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

const min = -5;
const max = 5;

function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min) + min); 
}
/*
function getRandomIntArray(n) {
    let array = [];
    for (let i = 0; i < n; i++) {
        array.push(getRandomInt(min, max));
    }
    return array;
}
*/

export default function Sheep({ ...props }) {
  const ref = useRef();
  const { nodes } = useGLTF("/sheepModel.gltf");
  const materials = new THREE.MeshStandardMaterial({ color: getRandomColor() })
  
  {/* makes sheep rotate */}
  useFrame((state, delta) => (ref.current.rotation.y += 0.01));

  // Hold state for hovered and clicked events
  const [hovered, hover] = useState(false);
  const [clicked, click] = useState(false);

  return (
      <mesh 
        {...props}
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Sheep.geometry}
        /* material={materials} */
        onPointerOver={(event) => hover(true)}
        onPointerOut={(event) => hover(false)}>
        <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} />
      </mesh>
  );
}

useGLTF.preload("/sheepModel.gltf");